
package ru.bpc.orach.hkl.billpayment.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://119.82.253.240/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * Testing service to verify Web Service is up
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WebServiceResponseTest", action = "http://119.82.253.240/WebServiceResponseTest")
    @WebResult(name = "WebServiceResponseTestResult", targetNamespace = "http://119.82.253.240/")
    @RequestWrapper(localName = "WebServiceResponseTest", targetNamespace = "http://119.82.253.240/", className = "ru.bpc.orach.hkl.billpayment.ws.WebServiceResponseTest")
    @ResponseWrapper(localName = "WebServiceResponseTestResponse", targetNamespace = "http://119.82.253.240/", className = "ru.bpc.orach.hkl.billpayment.ws.WebServiceResponseTestResponse")
    public String webServiceResponseTest();

    /**
     * Get <b>List of Bills</b> based on <b>Customer Number</b>. 
     * 
     * @param loginInfo
     * @param customerNumber
     * @return
     *     returns ru.bpc.orach.hkl.billpayment.ws.CustomerBills
     */
    @WebMethod(operationName = "GetCustomerBills", action = "http://119.82.253.240/GetCustomerBills")
    @WebResult(name = "GetCustomerBillsResult", targetNamespace = "http://119.82.253.240/")
    @RequestWrapper(localName = "GetCustomerBills", targetNamespace = "http://119.82.253.240/", className = "ru.bpc.orach.hkl.billpayment.ws.GetCustomerBills")
    @ResponseWrapper(localName = "GetCustomerBillsResponse", targetNamespace = "http://119.82.253.240/", className = "ru.bpc.orach.hkl.billpayment.ws.GetCustomerBillsResponse")
    public CustomerBills getCustomerBills(
        @WebParam(name = "CustomerNumber", targetNamespace = "http://119.82.253.240/")
        String customerNumber,
        @WebParam(name = "LoginInfo", targetNamespace = "http://119.82.253.240/")
        LoginInfo loginInfo);

    /**
     * Get <b>Bill Information</b> based on <b>Bill Number</b>. 
     * 
     * @param billNumber
     * @param loginInfo
     * @return
     *     returns ru.bpc.orach.hkl.billpayment.ws.BillInfo
     */
    @WebMethod(operationName = "GetBillInfo", action = "http://119.82.253.240/GetBillInfo")
    @WebResult(name = "GetBillInfoResult", targetNamespace = "http://119.82.253.240/")
    @RequestWrapper(localName = "GetBillInfo", targetNamespace = "http://119.82.253.240/", className = "ru.bpc.orach.hkl.billpayment.ws.GetBillInfo")
    @ResponseWrapper(localName = "GetBillInfoResponse", targetNamespace = "http://119.82.253.240/", className = "ru.bpc.orach.hkl.billpayment.ws.GetBillInfoResponse")
    public BillInfo getBillInfo(
        @WebParam(name = "BillNumber", targetNamespace = "http://119.82.253.240/")
        String billNumber,
        @WebParam(name = "LoginInfo", targetNamespace = "http://119.82.253.240/")
        LoginInfo loginInfo);

    /**
     * Update <b>Bill Payment Information</b> to PPWSA.
     * 
     * @param loginInfo
     * @param checksum
     * @param billPaymentInfo
     * @return
     *     returns ru.bpc.orach.hkl.billpayment.ws.UpdateStatus
     */
    @WebMethod(operationName = "UpdateBill", action = "http://119.82.253.240/UpdateBill")
    @WebResult(name = "UpdateBillResult", targetNamespace = "http://119.82.253.240/")
    @RequestWrapper(localName = "UpdateBill", targetNamespace = "http://119.82.253.240/", className = "ru.bpc.orach.hkl.billpayment.ws.UpdateBill")
    @ResponseWrapper(localName = "UpdateBillResponse", targetNamespace = "http://119.82.253.240/", className = "ru.bpc.orach.hkl.billpayment.ws.UpdateBillResponse")
    public UpdateStatus updateBill(
        @WebParam(name = "BillPaymentInfo", targetNamespace = "http://119.82.253.240/")
        BillPaymentInfo billPaymentInfo,
        @WebParam(name = "LoginInfo", targetNamespace = "http://119.82.253.240/")
        LoginInfo loginInfo,
        @WebParam(name = "Checksum", targetNamespace = "http://119.82.253.240/")
        String checksum);

}
